# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d496e3808218eb1e995f6f00f87a87aa60de15c5c3d1e9b5fa96e7f5b749d887833e1dc5ed2e402c066e130b2c2aea38ed587b19add7844bf7de425c90767a74

test:
  secret_key_base: d7491d9c86ce3132894b8b4a0c68aa489fd388283180cf9f83d54b26a063d4dbb0073f3b44fed2484d042c6c97e4fecfc2df7e3cdcc6fa333afcf1359c07c34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
